### ISSUE TITLE
HYYP App go Offline

### ISSUE THREAD

**Issue by Pieterjvr** [hawky358/hass_ids_hyyp#26] opened 2024-06-24 15:28 UTC
Hi All

Is it only my homeassistant cause the HYYP app to go offline and then HA also show it is offline.

Everytime I integrate HYYP with HA it work maybe for the first 30-60min then all hell break loose :) 

My HYYP on my mobile phone show offline as well as HYYP in HA.

Regards,
Pieter

**Comment by hawky358** [comment] 2024-06-24 16:21
Hello

1. When did this start?
2. Did it work before?
3. If you remove the integration from HASS does it fix the app?
4. Which version of the integration are you using?
5. Do you use IDS HYYP or ADT?
6. Do you use the GSM module?

There's not much to go on. Reproducing this may be quite difficult since it doesn't sound like anything locally.

**Comment by Pieterjvr** [comment] 2024-06-24 17:33
Hello

I notice this issue earlier this year and because I am not at home and could not leave the wife to struggle, I complete removed it.

First time I added it, was last year December and all work fine till yearly this year.

As soon as I remove or disable the HYYP integration, it takes about 45min for the HYYP app to be back online on my iPhone.

Currently running IDS 1.6.1. I update everything last night and reconfigured the up. Again, after about 45-60min all went offline again and was required to disable the integration in HA to get the mobile app to work.

I use IDS HYYP with an IDS x16 806 Series.

I have the GSM module on my panel.

Kind Regards,
Pieter

**Comment by hawky358** [comment] 2024-06-24 17:55
# #

> I have the GSM module on my panel.

I believe this is the issue.
There was another user who also had a GSM module ([Link to discussion](https://github.com/hawky358/hass_ids_hyyp/discussions/24)). I didn't know these modules existed.

In short the GSM module seems to be limited to 50MB per month.  From what you're saying there may be an hourly limit as well.

The integration currently polls every 30 seconds, which is not a problem for the "LAN" HYYP modules. But these small data packets add up when you have VERY limited data.

You can give version 1.7.0-b1 a try. I've added a "GSM Module Low data mode" to the integration.

- The low data mode only polls once every 30 minutes, thus significantly reducing the data usage (change log states 15, but I made it 30)
- The system still "instantly" refreshes if you do something like arm, disarm, bypass, etc.
- In order to support "anytime" refreshes I've added a button `button.[site_name]_refresh_button` which queues an immediate update. So you'll just have to make a "Refresh" button or something along those lines.
 - I know it "works" in the sense that it only polls every 30 minutes, but since I don't have a GSM module I can't test the issue of HYYP going offline.



See the screenshot in the changelog, which shows where to activate this.  (It's where you enter your codes)
[Changelog for 1.7.0-b1](https://github.com/hawky358/hass_ids_hyyp/tree/1.7.0-b1#changelog)

**Comment by hawky358** [comment] 2024-06-24 17:56
1.7.0-b1 is on the beta branch 

![image](https://github.com/hawky358/hass_ids_hyyp/assets/16265473/f37caef0-33ea-4906-a779-712f55a25dff)

**Comment by Pieterjvr** [comment] 2024-06-26 04:28
Thanks for this. I will give it ago over the weekend as I also need to try and setup my nspanel pro that I ordered.

I might have a spare hyyp with gsm that I can maybe borrow to you if you need to do test.  PM me then we can try arranging something.

Kind Regards,
Pieter

**Comment by kimfr** [comment] 2024-07-01 11:19
Hi there,

I'm "the other user" - I actually had to increase the time to 60 minutes. I gave up dealing with ADT and actually phoned IDs directly to confirm the 50MB - even with 30 min. refresh I manage to run out sometimes. This might be because we exclusively use the phone app as well and have made it a habit (good or bad) to always refresh before doing anything with our Alarm........

Would it be possible to have the GSM update interval as a variable/pick list?
Alternatively, I guess that I can just change the below line in const.py to:
GSM_MODE_POLL_TIME = 60*60 #60 Minutes

With the added feature of "Refresh" - I should be able to work around a much higher "poll time" - Thanks for adding this feature.

Thanks
Kim

**Comment by hawky358** [comment] 2024-07-01 11:39
Thanks for the feedback.
When initially implementing it, I was actually thinking about a field so that you can choose a poll time. Since this is still a test version I just hard coded it for now.

I'll take a look tonight to add an option where you can select the poll time when using the GSM Low data mode.

Due to the way it works I don't like the idea of text field, since you don't need that resolution in any event, so I was thinking a dropdown, with several options say 30mins, 60mins, 90mins, 120mins, Never/Manual.

That being said, what's the difference between say, 30 mins, 60 mins and "never" from a user perspective really? If it's already that long, you're probably not going to rely on it for automations etc. anyway.
The IDS App is in fact "Never" i.e. only manual.

So maybe just a 120mins and "Manual only". 
"Manual Only" will probably really mean something like once a day or longer.

It still refreshes immediately on arm, disarm, bypass etc. and you have a "Refresh" button and you get "Cell phone" notifications to HASS which can automate a refresh.

I personally am not going to use this feature, so what are your thoughts? Then I can see what I can implement.

**Comment by kimfr** [comment] 2024-07-01 12:19
Yeah, I suspect I would also just run it as “Manual” as my plan was to refresh on various “events” together with using HA to arm/disarm instead of Phone AppSo, a timed option and the “Manual Only” as a predefined selection is probably best. I would probably suggest 120 min. as with 60 min. I think you might be running to close to the “GSM Data limit” in some cases. ThanksKimSent from my iPhoneOn 01 Jul 2024, at 13:41, hawky358 ***@***.***> wrote:﻿
Thanks for the feedback.
When initially implementing it, I was actually thinking about a field so that you can choose a poll time. Since this is still a test version I just hard coded it for now.
I'll take a look tonight to add an option where you can select the poll time when using the GSM Low data mode.
Due to the way it works I don't like the idea of text field, since you don't need that resolution in any event, so I was thinking a dropdown, with several options say 30mins, 60mins, 90mins, 120mins, Never/Manual.
That being said, what's the difference between say, 30 mins, 60 mins and "never" from a user perspective really? If it's already that long, you're probably not going to rely on it for automations etc. anyway.
The IDS App is in fact "Never" i.e. only manual.
So maybe just a 120mins and "Manual only".
"Manual Only" will probably really mean something like once a day or longer.
It still refreshes immediately on arm, disarm, bypass etc. and you have a "Refresh" button and you get "Cell phone" notifications to HASS which can automate a refresh.
I personally am not going to use this feature, so what are your thoughts? Then I can see what I can implement.

**Comment by hawky358** [comment] 2024-07-01 18:54
I've published 1.7.0-b2.
I've replaced the tick box with a dropdown where you can select the polling times.
Currrently 30secs, 120min and Never*   (Never is currently once a day)

![gsmmode_poll](https://github.com/hawky358/hass_ids_hyyp/assets/16265473/d436edbd-9169-46d8-b7fc-5dde3a2dd966)

**Comment by hawky358** [comment] 2024-07-09 11:39
Were you able to see anything with this update or is it too short to be able to tell? i.e. you need around a month to see?

I've released 1.7.0-b4. Just some minor changes (24 hour option and Never = 1 week)

**Comment by kimfr** [comment] 2024-07-09 17:39
Sorry, haven't had much time for HA. I have updated to 1.7.0-b4 and changed the interval to "Never". Previously, I was running 60 min. and I was fine on the monthly basis. Will have to see at the end of the month.

Thanks for adding the refresh option, I will change how all the automation works as you added the "Refresh" - good for those cases where the alarm status is changed outside of HA (no names mentioned as to who might do that ;-) ).

**Comment by hawky358** [comment] 2024-07-09 19:50
No worries, no rush.
This is "your" feature after all.

I'm going to leave it as is for the next month or so.
Let's see what happens.

**Comment by Pieterjvr** [comment] 2024-07-14 09:28
Hi Hawky

Finally had some time today, but I can not get the beta switch in HACS. Am I doing something wrong?

Regards.
Pieter

**Comment by hawky358** [comment] 2024-07-14 10:49
Should be as simple as going to redownload and ticking the show beta option.
I can't recall that HACS had any settings that you could change on this.

https://github.com/user-attachments/assets/46e98665-d2bf-405b-82d0-b3e3a7c5a043

**Comment by hawky358** [comment] 2024-07-15 11:45
Hmm,
I don't think this has anything to do with that then. It happens too quickly I think, since the integration isn't really doing anything.

Are you logged into multiple phones via the app?
Can you try that if not and see whether something happens?
Wondering whether you have done sort of limitation on that.

**Comment by Pieterjvr** [comment] 2024-07-15 12:00
It happens on my wife’s phone as well. I think there is a limitation on HYYP GSM side, but cannot confirm this

**Comment by Pieterjvr** [comment] 2024-07-17 08:37
Hi Hawky

I gave it another go, but this time on the integration I did not select 24hour Polling first and changed it afterward to Never. It seems Like HA might keep some cache.

Currently 24hours later and the integration is set to Never Polling and both my HA and mobile app still online. Crossing fingers.

Do you perhaps have the visual code for the stay profile card for the dashboard. For some reason I cannot find it.

Kind Regards,
Pieter

From: Pieter Janse van Rensburg
Sent: Monday, July 15, 2024 2:00 PM
To: hawky358/hass_ids_hyyp ***@***.***>; hawky358/hass_ids_hyyp ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [hawky358/hass_ids_hyyp] HYYP App go Offline (Issue #26)

It happens on my wife’s phone as well. I think there is a limitation on HYYP GSM side, but cannot confirm this

**Comment by hawky358** [comment] 2024-07-17 09:15
Ok, it's possible that HA didn't pull in the new value. If the values are different between versions then HA "loses" the previous set time.  I'll fix the values once we "complete" the test. I'll also see if I can make a "Current poll interval" sensor.  Don't know how feasible it is, but I'll take a look. Just for information/verification.

Here's the link to my cards I previously posted. Again, a bit messy, but I haven't felt obligated to refactor 😄 .
Obviously all my entities are still in there, so you'll have to go through and check

https://github.com/hawky358/hass_ids_hyyp/discussions/14#discussioncomment-6376684

**Comment by hawky358** [comment] 2024-07-17 09:17
Let me know your results please.
I hope we can get this working for you.

**Comment by Pieterjvr** [comment] 2024-07-22 06:17
Hi Hawky

So I have been testing the beta last week the whole week and so far so good. What I notice was that the status did not update of when the alarm were on or off and I created a automation that refresh every hour the status. After implementing the automation my iPhone app went offline once, but I think it was due to me  triggering the automation a few times but it came back online again. Since then automation runs every hour and the status update without any app or integration go offline.

Here is my automation:
alias: Hourly Refresh Alarm Status
description: Hourly Refresh Alarm Status
trigger:
  - platform: time_pattern
    hours: "*"
condition: []
action:
  - service: button.press
    metadata: {}
    data: {}
    target:
      entity_id: <entity of your refresh button>
mode: single

**Comment by hawky358** [comment] 2024-07-22 06:52
What you can do for your tests is to also add a push notification to that automation in home assistant which sends you a notification to your cell phone whenever `sensor.[site]_ids_push_notifications` changes.  This way you can confirm that sensor is working and you can go check whether the alarm updated.

I personally don't use the IDS HYYP app at all, even the notifications (i.e. cell phone push notifications) are sent via home assistant using that sensor's values.

**Comment by hawky358** [comment] 2024-08-14 05:27
Hello,

From our discussions above it seems like we've identified that the issue seems to be a polling limit on IDS's side on the GSM module.
I've implemented a "fix" for this by means of selectable polling times and a refresh button which can be used in conjunction with the push notification sensor for example. It's not ideal, but we can't change how IDS systems work.

I've released 1.7.0 as a test release and will shortly move it over to the official release.
Please let me know if there are any other issues specifically related to this issue, otherwise I will close the issue as resolved.

**Comment by Pieterjvr** [comment] 2024-08-15 06:58
Hi Hawky

For some reason my push notification show unknown and I could not setup the automation up as per your suggestion. Even with the automation I did to press refresh refresh every hour worked well, but I also notice it twice where everything was unknown and I was required to reload the integration to get status back from the IDS. 

What I have done to mitigate this was to setup a new automation to reload the integration every 4hours and disable the press refresh every hours. I only notice it as well once that the mobile app show online but could not arm nor disarm my IDS, but this could have been something on IDS site. still testing and give some new feedback say in a week time.

**Comment by hawky358** [comment] 2024-08-15 07:17
Thanks for the feedback.

I wonder why your notifications is showing Unknown. 
Normally it will show unknown until you receive the first notification (e.g. arm/bypass/etc.) 

Can you try to re-add the integration as see if there are any warnings in the HASS logs?

**Comment by hawky358** [comment] 2024-10-04 09:54
Hello,

Have you seen anything new?
This GSM module seems to be quite weird for some reason.

**Comment by hawky358** [comment] 2024-11-05 14:50
Closing this issue as there hasn't been any further activity after implementing the fix, it should be "fixed" i.e. by using 1.7.3+ and using the "never" refresh option. Then using the refresh button as and when required.

1.8.2+ fixes/upgrades the FCM system which _should_ be more reliable.

**Closed by hawky358** 2024-11-05 14:50 UTC
